# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 8.0
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore NetPortfolio/NetPortfolio.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build NetPortfolio/NetPortfolio.csproj
      # echo Test started on `date`
      # dotnet test NetPortfolio/NetPortfolio.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 -o ./ NetPortfolio/NetPortfolio.csproj
      
artifacts:
  files:
    - NetPortfolio/**/*